language: go
go:
  - 1.5.1
  - 1.5.2
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
matrix:
  allow_failures:
    - go: tip
